services:
  devcontainer:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - HOST_DOCKER_GROUP_ID=$HOST_DOCKER_GROUP_ID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace/
    tty: true
    ports:
      - 9003:9003
